import assert from 'node:assert/strict';
import { getPolicy, evaluateAttempt, createClock } from './grading.mjs';

const score = (overrides = {}) => evaluateAttempt({correct:117, errors:0, elapsedMs:175500, challenge:true, interrupted:false, policy:getPolicy('3'), ...overrides});
assert.equal(getPolicy('3').speed, 8);
assert.equal(getPolicy('6').speed, 12);
assert.equal(getPolicy('6', true).speed, 8);
assert.throws(() => getPolicy('4'), RangeError);
assert.equal(score().passed, true, 'exactly 8 WPM passes');
assert.equal(score({elapsedMs:175501}).passed, false, 'rounded display does not determine passing');
assert.equal(score({policy:getPolicy('6')}).passed, false);
assert.equal(score({policy:getPolicy('6'),elapsedMs:117000}).passed, true);
assert.equal(score({errors:6}).passed, true);
assert.equal(score({errors:7,elapsedMs:10000}).passed, false, 'speed cannot offset low accuracy');
assert.equal(score({correct:95,errors:5,elapsedMs:10000}).passed, true, 'exactly 95% passes');
assert.equal(score({interrupted:true}).passed, false);
assert.equal(score({challenge:false,correct:90,errors:10,elapsedMs:999999,interrupted:true}).passed, true);
assert.equal(score({challenge:false,correct:89,errors:11}).passed, false);
assert.equal(score({correct:0,elapsedMs:0}).passed, false);
let now = 1000;
const clock = createClock(() => now);
now = 4000;
assert.equal(clock.elapsed(), 0, 'waiting before first key is not timed');
clock.start(); now += 2000; clock.start();
assert.equal(clock.elapsed(), 2000, 'subsequent key does not restart clock');
clock.pause(); now += 5000;
assert.equal(clock.elapsed(), 2000);
clock.resume(); now += 3000;
assert.equal(clock.elapsed(), 5000);
clock.pause();
assert.equal(clock.elapsed(), 5000);
console.log('PASS: grade policies, accuracy/speed boundaries, interrupted challenge, practice, monotonic clock.');
