const fs = require('node:fs');
const assert = require('node:assert/strict');
const asModule = s => 'data:text/javascript;base64,' + Buffer.from(s).toString('base64');
(async () => {
    const configUrl = asModule(fs.readFileSync('shared/reward-tree-config.js', 'utf8'));
    const config = await import(configUrl);
    const { deriveRewardTreeModel } = await import(asModule(fs.readFileSync('shared/reward-tree-model.js', 'utf8').replace('./reward-tree-config.js', configUrl)));
    const activities = config.getRewardTreeCourse('grade6-115-1').activities;
    const row = (key, completed = true, week = '05') => ({ course_id: 'grade6-115-1', week_code: week, activity_key: key, completed, current_level: key === 'typing_task_5' ? 5 : 1 });
    const base = [row('typing_task_5', true, '03'), row('typing_task_5')];
    assert.equal(deriveRewardTreeModel(base, activities).stats.flowerCount, 2);
    const all = [...base, row('typing_boss_zh_1'), row('typing_boss_en_1')];
    const model = deriveRewardTreeModel(all, activities);
    assert.equal(model.stats.leafCount, 8);
    assert.equal(model.stats.flowerCount, 4);
    assert.equal(model.stats.skippedActivityCount, 0);
    assert.equal(model.stats.unknownRowCount, 0);
    assert.equal(deriveRewardTreeModel([...all, row('typing_boss_zh_1')], activities).stats.flowerCount, 4);
    assert.equal(deriveRewardTreeModel([...base, row('typing_boss_zh_1', false)], activities).stats.flowerCount, 2);
    assert.equal(deriveRewardTreeModel([...base, row('typing_boss_en_1')], activities).stats.flowerCount, 3);
    assert.equal(deriveRewardTreeModel([{...row('typing_boss_zh_1'),course_id:'grade3-115-1'}], activities).stats.flowerCount, 0);
    const { challenges } = await import(asModule(fs.readFileSync('grade6/115-1/week05-typing-data.js','utf8')));
    assert.equal(new Set(Object.values(challenges).map(c=>c.key)).size, 3);
    assert.equal(challenges.regular.levels.length, 5);
    assert.equal(challenges.zh.levels[0].ans.split('\n').length, 25);
    assert.equal(challenges.en.levels[0].ans.split('\n').length, 9);
    console.log('PASS: ordinary rewards, independent bosses, deduplication, reset, course isolation, question data');
})().catch(e => {console.error(e);process.exitCode=1;});
