import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
import path from 'node:path';
const require = createRequire(path.join(process.env.TEMP, 'codex-drive-validation', 'package.json'));
const { PGlite } = require('@electric-sql/pglite');
const teacher='00000000-0000-0000-0000-000000000001', student='00000000-0000-0000-0000-000000000002', other='00000000-0000-0000-0000-000000000003';
test('real SQL roles, roster isolation, 100 MB reserve, review version, atomic events and retries',async()=>{
 const db=new PGlite();
 try{
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);
 create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.uid',true),'')::uuid$$;
 create function public.is_teacher() returns boolean language sql as $$select auth.uid()='${teacher}'::uuid$$;
 create table public.student_enrollments(school_year smallint,email text,class_code text,seat_no smallint,display_name text);
 create table public.drive_connections(owner_user_id uuid);
 insert into auth.users values('${teacher}','teacher@test',now()),('${student}','student@test',now()),('${other}','other@test',now());
 insert into public.student_enrollments values(115,'student@test','601',1,'Student'),(115,'other@test','602',1,'Other');
 insert into public.drive_connections values('${teacher}');
 grant usage on schema public,auth to anon,authenticated,service_role;`);
 const sql=await readFile(new URL('../../supabase/homework.sql',import.meta.url),'utf8');await db.exec(sql);await db.exec(sql);
 const as=async(uid,role='authenticated')=>{await db.exec('reset role');await db.query("select set_config('test.uid',$1,false)",[uid]);await db.exec(`set role ${role}`);};
 const action=async(a,d={})=>(await db.query('select public.homework_action($1,$2) as data',[a,JSON.stringify(d)])).rows[0].data;
 await as(teacher);const a=await action('create',{week_code:'01',class_code:'601',title:'Test video',instructions:'Upload MP4'});
 await as(student);assert.equal((await action('list')).assignments.length,0);
 await assert.rejects(action('create',{week_code:'01',class_code:'*',title:'forged'}),/teacher_required/);
 await assert.rejects(action('upload_context',{assignment_id:a.id}),/assignment_unavailable/);
 for(const t of ['homework_assignments','homework_uploads','homework_submissions','homework_events','homework_settings'])await assert.rejects(db.query(`select * from public.${t}`),/permission denied/);
 await assert.rejects(db.query('select public.homework_finalize($1,$2)',[student,student]),/permission denied/);
 await as(teacher,'service_role');await db.query('update public.homework_assignments set drive_folder_id=$1 where id=$2',['folder',a.id]);
 await as(teacher);await action('set_state',{assignment_id:a.id,state:'open'});
 await as(other);assert.equal((await action('list')).assignments.length,0);await assert.rejects(action('upload_context',{assignment_id:a.id}),/assignment_unavailable/);
 await as(student);assert.equal((await action('list')).max_file_bytes,104857600);assert.equal((await action('upload_context',{assignment_id:a.id})).id,a.id);
 await as(teacher,'service_role');
 const reserve=async(id,name='canva.mp4',size=20*1024*1024)=> (await db.query('select public.homework_reserve($1,$2,$3,$4,$5,$6,$7) as data',[student,a.id,id,`drive-${id}`,name,size,'a'.repeat(64)])).rows[0].data;
 const first='10000000-0000-0000-0000-000000000001', second='10000000-0000-0000-0000-000000000002';
 await assert.rejects(reserve(first,'big.mp4',104857601),/file_size/);
 await reserve(first);await reserve(first);await assert.rejects(reserve(first,'changed.mp4'),/upload_conflict/);
 const finalize=id=>db.query('select public.homework_finalize($1,$2)',[student,id]);
 await finalize(first);await finalize(first);
 assert.equal((await db.query('select count(*)::int as n from public.homework_events')).rows[0].n,1);
 await as(teacher);const roster=await action('roster',{assignment_id:a.id});assert.equal(roster.students.length,1);assert.equal(roster.students[0].status,'submitted');
 const review={assignment_id:a.id,user_id:student,upload_id:first,status:'passed',feedback:'Good'};
 await action('review',review);await action('review',review);
 await as(student);const listed=await action('list');assert.equal(listed.assignments[0].submission.status,'passed');assert.ok(!JSON.stringify(listed).includes('resume_uri'));
 await assert.rejects(action('review',review),/teacher_required/);
 await as(teacher,'service_role');await reserve(second);await finalize(second);await finalize(first);
 assert.equal((await db.query('select count(*)::int as n from public.homework_events')).rows[0].n,3);
 await as(teacher);await assert.rejects(action('review',review),/version_changed/);
 await as(student);assert.equal((await action('list')).assignments[0].submission.status,'submitted');
 await as(teacher);await action('set_state',{assignment_id:a.id,state:'closed'});
 await as(student);await assert.rejects(action('upload_context',{assignment_id:a.id}),/assignment_unavailable/);
 await as('', 'anon');await assert.rejects(action('list'),/permission denied/);
 }finally{await db.close();}
});
