import {readingRequest,readingSources,readingLabels} from './reading-api.js';
const el=(tag,text='',cls='')=>{const n=document.createElement(tag);n.textContent=text;n.className=cls;return n;};
const button=(text,fn,cls='')=>{const b=el('button',text,cls);b.type='button';b.onclick=fn;return b;};
const label=(text,input)=>{const l=el('label',text);l.append(input);return l;};
const dates=p=>`第 ${Number(p.week_code)} 週｜${p.starts_on}～${p.ends_on}`;
export function initReading({root,teacher=false}){
 let session=null,generation=0,busy=false,reloadPending=false,periods=[],rows=[],chosen=null;
 const dialogs=new Set();
 const message=el('p','確認閱讀服務中…','note'),body=el('div');root.append(message,body);
 function modal(title){const d=el('dialog','','reading-dialog');const head=el('div','','dialog-head');head.append(el('h2',title),button('關閉 ×',()=>d.close(),'secondary'));const content=el('div');const notice=el('p','','note');notice.setAttribute('role','status');d.append(head,content,notice);document.body.append(d);dialogs.add(d);d.addEventListener('close',()=>{dialogs.delete(d);d.remove();});d.showModal();return {d,content,notice};}
 async function call(action,data={}){const g=generation;const r=await readingRequest(session,action,data);if(g!==generation)throw new Error('登入帳號已改變，請重新開啟。');return r;}
 async function run(fn,notice=message){if(busy)return;busy=true;const g=generation;root.querySelectorAll('button').forEach(b=>b.disabled=true);dialogs.forEach(d=>d.querySelectorAll('button').forEach(b=>b.disabled=true));try{await fn();}catch(e){if(g===generation)notice.textContent=e.message;}finally{busy=false;if(g===generation){root.querySelectorAll('button').forEach(b=>b.disabled=false);dialogs.forEach(d=>d.querySelectorAll('button').forEach(b=>b.disabled=false));}if(reloadPending){reloadPending=false;if(session?.user)await run(load);}}}
 function resources(){const box=el('div','','reading-resources');for(const [title,url] of [['頂溪國小數位圖書館 ↗','https://thpsntpc.ebook.hyread.com.tw/'],['新北市親師生平台 ↗','https://pts.ntpc.edu.tw/']]){const a=el('a',title,'button secondary');a.href=url;a.target='_blank';a.rel='noopener noreferrer';box.append(a);}return box;}
 async function load(){const r=await call('list');periods=r.periods;message.textContent=teacher?'閱讀為自願分享，只列已分享的小卡，不列缺交。':'讀到想分享的書，再來留下你的發現。每週一張，可以修改。';render();}
 function editor(p){const v=p.submission;const {d,content,notice}=modal(dates(p));content.append(el('p','閱讀小卡・自由參與。修改會保留先前版本。','note'),resources());const f=el('form'),source=el('select'),book=el('input'),text=el('textarea');source.required=book.required=text.required=true;book.maxLength=100;text.maxLength=500;source.append(new Option('選擇閱讀入口',''));for(const [k,name] of Object.entries(readingSources))source.append(new Option(name,k));source.value=v?.source||'';book.value=v?.book||'';text.value=v?.reflection||'';text.placeholder='我想知道……／我發現……';f.append(label('你從哪裡找到它？',source),label('這本書叫什麼名字？',book),label('說說你的發現',text),el('p','用自己的話寫就好，不用寫很長。','note'));const send=el('button',v?'儲存修改版本':'分享本週閱讀');send.type='submit';f.append(send);content.append(f);let retry=null;
 f.onsubmit=e=>{e.preventDefault();if(!book.value.trim()||!text.value.trim())return;run(async()=>{const payload={period_id:p.id,expected_version:v?.id||null,source:source.value,book:book.value.trim(),reflection:text.value.trim()};const signature=JSON.stringify(payload);if(retry&&retry.signature!==signature){notice.textContent='前次送出結果未確認，請先關閉視窗並更新紀錄，再修改內容。';return;}retry??={signature,id:crypto.randomUUID()};await call('submit',{...payload,id:retry.id});d.close();await load();message.textContent='本週閱讀已分享，謝謝你留下自己的發現！';},notice);};}
 async function history(p,user=null,name='我的閱讀小卡'){
 const {d,content,notice}=modal(`${dates(p)}・${name}`);await run(async()=>{const r=await call('history',{period_id:p.id,...(user?{user_id:user}:{})});if(!d.isConnected)return;
 if(!r.versions.length){content.append(el('p','這一週還沒有分享紀錄。'));return;}
 r.versions.forEach((v,i)=>{const card=el('article','','reading-version');card.append(el('h3',`第 ${r.versions.length-i} 版${v.latest?'・最新版':''}`),el('span',readingLabels[v.status],`badge ${v.status}`),el('p',`${readingSources[v.source]} · ${new Date(v.submitted_at).toLocaleString('zh-TW')}`,'note'),el('h3',v.book),el('p',v.reflection,'feedback'));
 if(teacher&&v.latest){const input=el('textarea');input.maxLength=2000;input.value=v.feedback;card.append(label('老師文字回饋',input),button('儲存回饋',()=>run(async()=>{await call('review',{period_id:p.id,user_id:user,version_id:v.id,review_seq:v.review_seq,feedback:input.value});d.close();await loadRoster(p);},notice)));
 }else card.append(el('p',v.feedback?`老師回饋：${v.feedback}`:'這個版本尚無文字回饋。','feedback'));content.append(card);});},notice);
 }
 async function loadRoster(p){chosen=p;const r=await call('roster',{period_id:p.id});rows=r.students;render();}
 function config(p=null){const {d,content,notice}=modal(p?'調整閱讀週次':'設定學期閱讀週次');content.append(el('p','依學期行事曆設定。沒上課的週可略過，不重新編號；已開放的舊週持續提供補分享。','note'));const f=el('form'),week=el('input'),start=el('input'),end=el('input'),enabled=el('select');week.type='number';week.min=1;week.max=22;week.required=start.required=end.required=true;week.value=p?Number(p.week_code):'';week.disabled=!!p;start.type=end.type='date';start.value=p?.starts_on||'';end.value=p?.ends_on||'';enabled.append(new Option('提供分享','true'),new Option('暫停分享（保留既有紀錄）','false'));enabled.value=String(p?.enabled??true);f.append(label('學期週次',week),label('開始日期',start),label('結束日期',end),label('狀態',enabled));const save=el('button','儲存週次');save.type='submit';f.append(save);content.append(f);f.onsubmit=e=>{e.preventDefault();run(async()=>{await call('configure',{week_code:String(Number(week.value)).padStart(2,'0'),starts_on:start.value,ends_on:end.value,enabled:enabled.value==='true'});d.close();await load();},notice);};}
 function render(){body.replaceChildren();if(!session?.user)return;
 if(teacher){body.append(button('設定學期閱讀週次',()=>config(),'secondary'));const settings=el('div','','reading-periods');periods.forEach(p=>{const item=el('div','','toolbar');item.append(el('span',`${dates(p)}${p.enabled?'':'・暫停分享'}`),button('查看分享',()=>run(()=>loadRoster(p)),'secondary'),button('調整',()=>config(p),'reading-link'));settings.append(item);});body.append(settings);if(!periods.length)body.append(el('p','先設定有上課的學期週次，不會自動產生缺號週。','note'));
 if(chosen){body.append(el('h3',dates(chosen)));const filters=el('div','','hw-filters'),cls=el('select'),state=el('select'),search=el('input'),grid=el('div','','hw-gallery reading-gallery');cls.append(new Option('全部班級',''));[...new Set(rows.map(r=>r.class_code))].sort().forEach(c=>cls.append(new Option(c+' 班',c)));state.append(new Option('全部已分享',''));Object.entries(readingLabels).forEach(([k,t])=>state.append(new Option(t,k)));search.placeholder='姓名或座號';filters.append(label('班級',cls),label('顯示',state),label('搜尋',search));body.append(filters,grid);
 const draw=()=>{grid.replaceChildren();const filtered=rows.filter(r=>(!cls.value||r.class_code===cls.value)&&(!state.value||r.status===state.value)&&`${r.display_name} ${r.seat_no}`.includes(search.value.trim()));filtered.forEach(v=>{const card=el('article','','hw-card reading-card'),wrap=el('div','','hw-card-body');wrap.append(el('h3',`${v.class_code}・${v.seat_no} 號 ${v.display_name}`),el('span',readingLabels[v.status],`badge ${v.status}`),el('p',readingSources[v.source],'note'),el('h3',v.book),el('p',v.reflection,'reading-excerpt'));const actions=el('div','','hw-quick');for(const status of ['passed','needs_revision',...(v.status==='submitted'?[]:['submitted'])])actions.append(button(status==='passed'?'過關':status==='needs_revision'?'再努力':'收回評比',()=>run(async()=>{await call('review',{period_id:chosen.id,user_id:v.user_id,version_id:v.id,review_seq:v.review_seq,status});await loadRoster(chosen);message.textContent='評比已保存，葉子依最新狀態計算。';}),status==='passed'?'':'secondary'));wrap.append(actions,button('查看小卡・繳交歷史',()=>history(chosen,v.user_id,v.display_name),'reading-link'));card.append(wrap);grid.append(card);});if(!filtered.length)grid.append(el('p','這個篩選條件下還沒有分享。','note'));};cls.onchange=state.onchange=search.oninput=draw;draw();}return;}
 body.append(resources());const current=periods.find(p=>p.current&&p.enabled);const summary=el('div');body.append(summary);if(current){summary.append(el('p',dates(current),'note'));if(current.submission)summary.append(el('span','本週已分享','badge submitted'),el('h3',current.submission.book),el('p',current.submission.feedback||current.submission.status==='needs_revision'?'老師有話想對你說，點開紀錄看看。':'謝謝你的閱讀分享。'));else summary.append(el('p','這週讀到什麼有趣的書？歡迎留下書名和一句想法。'));summary.append(button(current.submission?'查看／修改本週小卡':'分享本週閱讀',()=>editor(current)));if(current.submission)summary.append(button('老師回饋與歷史',()=>history(current),'reading-link'));}else summary.append(el('p','這一週沒有安排閱讀小卡，仍可回到已開放的週次分享。','note'));
 const past=el('details','','reading-past');past.append(el('summary','歷週閱讀・補分享與修改'));periods.slice().reverse().forEach(p=>{const row=el('div','','toolbar');row.append(el('span',dates(p)),el('span',p.submission?'已分享':'歡迎分享','note'));if(p.enabled)row.append(button(p.submission?'修改小卡':'分享這一週',()=>editor(p),'secondary'));if(p.submission)row.append(button('紀錄與回饋',()=>history(p),'reading-link'));past.append(row);});if(!periods.length)past.append(el('p','閱讀週次由老師依學期安排開放。','note'));body.append(past);
 }
 return {async setSession(next){generation++;session=next;periods=[];rows=[];chosen=null;dialogs.forEach(d=>d.close());body.replaceChildren();reloadPending=false;if(!next?.user){message.textContent='登入學校帳號後，就可以分享與查看自己的閱讀紀錄。';return;}message.textContent='讀取閱讀紀錄中…';if(busy){reloadPending=true;return;}await run(load);},refresh:()=>{if(session?.user)return run(load);}};
}
